[project]
name = "icu-typ-docs"
version = "0.1.0"
dependencies = [
    "mkdocs-material >= 9.5",
    "mkdocs-git-revision-date-localized-plugin >= 1.2",
    "pygments @ git+https://github.com/Nerixyz/pygments@db6bbf896344ffd814c839ee01f860c249ab596e",
]
