name: Deploy to Pages

on:
    push:
        branches: ["main", "master"]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build-docs:
        uses: ./.github/workflows/build-docs.yml

    deploy:
        needs: [build-docs]
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Setup Pages
              uses: actions/configure-pages@v5

            - uses: actions/download-artifact@v6
              with:
                  name: build-main
                  path: build

            - uses: actions/download-artifact@v6
              with:
                  name: build-v0.2.0
                  path: build/v0.2.0

            - uses: actions/download-artifact@v6
              with:
                  name: build-v0.1.2
                  path: build/v0.1.2

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  path: "build"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
